services:
  - type: web
    name: plant-or-admin
    runtime: static
    rootDir: admin-web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_SANITY_PROJECT_ID
        sync: false
      - key: VITE_SANITY_DATASET
        sync: false
      - key: VITE_SANITY_TOKEN
        sync: false
